tittle: Kasper Østerlie Gladsøy
<img align="left" width="100" height="100" src="https://scontent-arn2-1.xx.fbcdn.net/v/t1.6435-9/102674069_545426212793147_207725425808565720_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=6ee11a&_nc_ohc=EcQb_uySFL8Q7kNvgETgRSS&_nc_ht=scontent-arn2-1.xx&_nc_gid=A6ORj95wqW50cQ9oTIA-FbD&oh=00_AYBSlnYSr_lyUMtuZuE9SJCdnlLhcO5DhTUjMsmq33-h_g&oe=672C69ED">
#logo: /assets/img/headshot_circle.png
#description: text below image
show_downloads: true
# theme: jekyll-theme-minima
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
